'use client';
import {useState} from 'react';
import Navigation from '../components/Navigation';
import {usePreferences} from '../components/PreferencesProvider';
import {useDashboard} from '../components/useDashboard';
import {validatePreferences,type Preferences} from '@/lib/preferences';
import {USE_CASES} from '@/lib/decision-model';
export default function Settings(){
  const {preferences,ready,save,error,refresh}=usePreferences(),[edited,setDraft]=useState<Preferences|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const draft=edited??preferences;
  const {data}=useDashboard(draft.city);
  function number(key:keyof Preferences,label:string,min:number,max:number,step=1){return <label key={key}>{label}<input type="number" value={draft[key] as number} min={min} max={max} step={step} required onChange={e=>setDraft({...draft,[key]:e.target.value===''?NaN:Number(e.target.value)})}/></label>;}
  return <main className={`dashboard city-${draft.city}`}><Navigation active="settings"/><div className="workspace"><header className="page-title"><p>YOUR BUYING BRIEF</p><h1>购房设置</h1><span>统一影响筛选、评分和贷款测算。设置仅属于当前访客，不展示给其他人。</span></header>
    <form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await save(validatePreferences(draft));setMessage('已保存。筛选与评分已更新，后台外部数据刷新已排队（每小时检查）。');}catch(e){setMessage(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}}>
      <section className="panel"><h2>预算与住房偏好</h2><div className="form-grid"><label>默认城市<select value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value as Preferences['city']})}><option value="hangzhou">杭州</option><option value="nanjing">南京</option></select></label>{number('purchaseYear','计划购房年份',2026,2060)}{number('cash','可用现金 / 万元',0,100000)}{number('budgetMin','总成本下限 / 万元',0,100000)}{number('budgetMax','总成本上限 / 万元',1,100000)}{number('areaMin','面积下限 / ㎡',10,2000)}{number('areaMax','面积上限 / ㎡',10,2000)}<label>住房类型<select value={draft.housingType} onChange={e=>setDraft({...draft,housingType:e.target.value as Preferences['housingType']})}><option value="new">新房</option><option value="resale">二手房</option><option value="all">不限</option></select></label></div></section>
      <section className="panel"><h2>资产偏好与就业中心</h2><div className="form-grid"><label>购房用途<select value={draft.useCase} onChange={e=>setDraft({...draft,useCase:e.target.value as Preferences['useCase']})}>{Object.entries(USE_CASES).map(([id,v])=><option key={id} value={id}>{v.label} · 时机{v.timing*100}% / 资产{v.asset*100}%</option>)}</select></label><label>通勤方式<select value={draft.commuteMode} onChange={e=>setDraft({...draft,commuteMode:e.target.value as Preferences['commuteMode']})}><option value="transit">公共交通</option><option value="drive">驾车</option></select></label><label className="checkbox-label"><input type="checkbox" checked={draft.school} onChange={e=>setDraft({...draft,school:e.target.checked})}/>开启学区需求（5%）</label></div><h3>{draft.city==='hangzhou'?'杭州':'南京'}就业中心权重</h3><div className="form-grid">{draft.baskets[draft.city].map((c,i)=><label key={c.id}>{c.name} / %<input type="number" min="0" max="100" value={c.weight} onChange={e=>setDraft({...draft,baskets:{...draft.baskets,[draft.city]:draft.baskets[draft.city].map((x,j)=>j===i?{...x,weight:Number(e.target.value)}:x)}})}/></label>)}</div><p className="muted">各城市权重合计须为 100%。未指定地址的“其他”不伪造通勤。学校默认不参与。</p></section>
      <section className="panel"><h2>资金与预留</h2><div className="form-grid">{number('loan','贷款本金 / 万元',0,100000)}{number('years','贷款期限 / 年',1,30)}{number('rateSpread','LPR 加点 / BP',-500,1500)}{number('parking','车位预留 / 万元',0,10000)}{number('fitout','整备预留 / 万元',0,10000)}{number('taxReserve','税费及其他预留 / 万元',0,10000)}</div><p className="muted">预留金额是你设定的预算，不是税费核定。<a href="/cashflow">查看现金流测算 →</a></p></section>
      <div className="save-bar"><span role="status">{message||error||'个人设置保存在服务器；清除访客 Cookie 后将无法找回匿名设置。'}</span><button className="primary" disabled={!ready||busy}>{busy?'正在保存…':'保存并刷新'}</button></div>
    </form>
    <section className="panel"><h2>刷新记录</h2>{refresh.length?refresh.map(r=><p key={r.city}>{r.city==='hangzhou'?'杭州':'南京'} · {r.status==='pending'?'等待后台采集':r.status==='completed'?'刷新完成':'部分来源更新成功'} · {r.completedAt??r.requestedAt}{r.note&&` · ${r.note}`}</p>):<p>暂无手动刷新请求。公共市场数据每日自动更新。</p>}<button type="button" onClick={()=>location.reload()}>重新读取状态</button></section>
    <section><div className="section-head"><h2>来源与健康</h2><span>仅此页展示采集细节</span></div><div className="sources">{data.sources.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer"><div><b>{s.name}</b><em>{s.quality==='verified'?'已核验':s.quality==='stale'?'最近尝试失败':'未核验'}</em></div><span>发布 {s.publishedAt} · 有效采集 {s.collectedAt?.slice(0,10)}</span><small>{s.note??s.basisVersion}</small></a>)}</div></section>
    </div></main>;
}
